# Generated by Django 2.1.5 on 2019-02-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20190217_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
